apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config-pvc
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-media-pvc
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-mybook-pvc
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 466Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-passport-pvc
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1900Gi
