apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/filebrowser
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-media-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-mybook-pv
spec:
  capacity:
    storage: 466Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/MyBook500GB
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-passport-pv
spec:
  capacity:
    storage: 1900Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/Passport2TB
