apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  namespace: jellyfin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/jellyfin/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache-pv
  namespace: jellyfin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/jellyfin/cache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-series-pv
  labels:
    type: jellyfin-series
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/media/series
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-filmes-pv
  labels:
    type: jellyfin-filmes
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/media/filmes
