apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv
  namespace: transmission
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/transmission/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-pv
  namespace: transmission
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /opt/media/downloads
