apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-pvc
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 200Gi
